name: Docker release

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and latest
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT=${{ github.sha }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shadowtest:latest, ${{ secrets.DOCKERHUB_USERNAME }}/shadowtest:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
