name: GoGitops
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: GoGitOps
        id: gogitops
        uses: beaujr/gogitops-action@v0.2
        with:
          github-actions-token: ${{secrets.GITHUB_TOKEN}}
